[package]
authors = ["Fabien Bellanger <valentil@gmail.com>"]
edition = "2018"
name = "test-actix"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-cors = "0.3.0"
actix-http = "2"
actix-service = "1.0.6"
actix-web = "3"
config = "0.10"
dotenv = "0.15"
env_logger = "0.7"
failure = "0.1.8"
futures = "0.3"
serde = "1.0"
serde_json = "1.0"
