[package]
name = "test-actix"
version = "0.1.0"
authors = ["Fabien Bellanger <valentil@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "2"
actix-rt = "1"
actix-http = "1"
serde = "1.0"
serde_json = "1.0"
env_logger = "0.7"
failure = "0.1.8"
futures = "0.3"
