version: '3'

services:
  mysql:
    container_name: rocket-mysql
    image: mysql:5.7
    restart: "no"
    volumes:
      - data_mysql:/var/lib/mysql
    ports:
    - 3307:3306
    environment:
      - MYSQL_DATABASE=rocket
      - MYSQL_USER=rocket
      - MYSQL_PASSWORD=rocket
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
    networks:
      - bridge

  phpmyadmin:
    container_name: rocket-phpmyadmin
    image: phpmyadmin/phpmyadmin
    restart: "no" # unless-stopped
    ports:
      - 7788:80
    environment:
      - PMA_HOST=rocket-mysql
      - PMA_USER=rocket
      - PMA_PASSWORD=rocket
    networks:
      - bridge

networks:
  bridge:

volumes:
  data_mysql: