version: '3.8'

services:
  api:
    container_name: actix-api
    build: .
    ports: 
      - "8090:8089"
    restart: "no" # on-failure
    volumes:
      - ./:/app
    depends_on:
      - mysql
    networks:
      - actix_bridge

  mysql:
    container_name: actix-mysql
    image: mysql:5.7
    restart: "no" # on-failure
    volumes:
      - actix_data_mysql:/var/lib/mysql:delegated
    environment:
      - MYSQL_DATABASE=actix
      - MYSQL_USER=actix
      - MYSQL_PASSWORD=actix
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
    networks:
      - actix_bridge

networks:
  actix_bridge:
    driver: bridge

volumes:
  actix_data_mysql:
    driver: local
